import ProductGrid from "./components/ProductGrid"
const Arrow=()=> <span className="arrow" aria-hidden="true"/>
export default function Home(){return <main id="top">
 <section className="hero"><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">Есен / Зима 2026</p><h1>Кожа,<br/><em>с характер.</em></h1><p className="lede">Вечни силуети. Мека естествена кожа. Якета, които стават по-добри с всяка история, изживяна в тях.</p><div className="hero-links"><a href="/women">За жени <Arrow/></a><a href="/men">За мъже <Arrow/></a></div></div><p className="hero-note">Проектирано в София · Създадено за движение</p></section>
 <section className="story section" id="story"><p className="index">01 / Нашата философия</p><div><h2>Не просто яке.<br/><em>Твоята втора кожа.</em></h2><p>Mojo Leather създава вечни връхни дрехи за хора, които живеят по свои правила. Всеки модел е скроен да носи лекота още от първия ден — и с времето да стане неподражаемо твой.</p><a className="text-link" href="#craft">Повече за нас <Arrow/></a></div></section>
 <section className="collection section" id="shop"><p className="index">02 / Колекцията</p><div className="section-head"><h2>Кожа без правила.<br/><em>Стил без срок.</em></h2><div className="tabs"><a href="#shop">Всички</a><a href="/women">Жени</a><a href="/men">Мъже</a></div></div><ProductGrid/><a className="all-products" href="/women">Виж продуктите <span>(4)</span> <Arrow/></a></section>
 <section className="category-split"><article><img src="https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1400&q=90" alt="Жена с черно кожено яке"/><div><p>За нея</p><h2>Нежна сила.</h2><a href="/women">Разгледай за жени <Arrow/></a></div></article><article><img src="https://images.unsplash.com/photo-1559551409-dadc959f76b8?auto=format&fit=crop&w=1400&q=90" alt="Мъж с кожено яке"/><div><p>За него</p><h2>Тих бунтар.</h2><a href="/men">Разгледай за мъже <Arrow/></a></div></article></section>
 <section className="craft section" id="craft"><div className="craft-image"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1400&q=90" alt="Човек с кожено яке"/></div><div className="craft-copy"><p className="index">03 / Създадено с мисъл</p><h2>Направено<br/><em>да стане твое.</em></h2><p>От отговорно добита пълнозърнеста кожа до ръчно завършени ръбове и метални елементи, които стареят красиво — обръщаме внимание на онова, което другите пропускат.</p><dl><div><dt>01</dt><dd>Премиум пълнозърнеста кожа</dd></div><div><dt>02</dt><dd>Производство в малки серии</dd></div><div><dt>03</dt><dd>Създадено за поправка</dd></div></dl><a className="text-link" href="/blog">Прочети гида за материали <Arrow/></a></div></section>
 <section className="services"><div><b>01</b><h3>Безплатна доставка</h3><p>За поръчки над €250</p></div><div><b>02</b><h3>30 дни за връщане</h3><p>Лесно и безплатно</p></div><div><b>03</b><h3>2 години грижа</h3><p>Поправките са от нас</p></div><div><b>04</b><h3>Личен стилист</h3><p>Говори с нашия екип</p></div></section>
 <section className="newsletter"><p className="index">Вътрешният кръг</p><h2>Добри истории.<br/><em>Страхотна кожа.</em></h2><p>Нови модели, съвети за грижа и ранен достъп — само когато има какво да кажем.</p><form><input type="email" placeholder="Твоят имейл адрес" aria-label="Имейл адрес"/><button>Абонирай се</button></form></section>
 </main>}
