"use client"
import{useState,type FormEvent}from"react"
import{beginGoogleLogin,requestPasswordReset}from"../lib/medusa"
import{useCommerce}from"./CommerceProvider"
export default function AccountClient(){
 const{customer,orders,authBusy,login,register,logout}=useCommerce();const[mode,setMode]=useState<"login"|"register"|"forgot">("login"),[error,setError]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState(false)
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");setSuccess("");setBusy(true);const form=new FormData(event.currentTarget);try{if(mode==="login")await login(String(form.get("email")),String(form.get("password")));else if(mode==="register")await register({email:String(form.get("email")),password:String(form.get("password")),first_name:String(form.get("first_name")),last_name:String(form.get("last_name"))});else{await requestPasswordReset(String(form.get("email")));setSuccess("Ако този имейл съществува, изпратихме инструкции за нова парола.")}}catch(e){setError(e instanceof Error?e.message:"Възникна грешка.")}finally{setBusy(false)}}
 const google=async()=>{setError("");setBusy(true);try{const result=await beginGoogleLogin(`${window.location.origin}/account/google-callback`);if(result.location)window.location.assign(result.location);else setError("Google входът още не е конфигуриран.")}catch(e){setError(e instanceof Error?e.message:"Google входът не е достъпен.")}finally{setBusy(false)}}
 if(authBusy)return <main className="account-page"><p>Зареждаме профила…</p></main>
 if(customer)return <main className="account-page"><div className="account-heading"><div><p className="eyebrow">Моят профил</p><h1>Здравей, {customer.first_name||customer.email}.</h1></div><button onClick={logout}>Изход</button></div><section className="account-details"><h2>Данни</h2><p>{customer.first_name} {customer.last_name}</p><p>{customer.email}</p></section><section className="account-orders"><h2>Моите поръчки</h2>{!orders.length?<p>Все още нямаш поръчки.</p>:orders.map(order=><article key={order.id}><div><strong>Поръчка #{order.display_id}</strong><span>{new Date(order.created_at).toLocaleDateString("bg-BG")}</span></div><div><span>{order.fulfillment_status||order.status}</span><strong>€{order.total}</strong></div></article>)}</section></main>
 return <main className="auth-page"><section className="auth-card"><p className="eyebrow">Furia Leather</p><h1>{mode==="login"?"Вход":mode==="register"?"Създай профил":"Нова парола"}</h1>{mode!=="forgot"&&<button className="google-button" type="button" onClick={google} disabled={busy}><span>G</span> Продължи с Google</button>}<div className="auth-divider"><span>или</span></div><form onSubmit={submit}>{mode==="register"&&<div className="name-fields"><label>Име<input name="first_name" required/></label><label>Фамилия<input name="last_name" required/></label></div>}<label>Имейл<input name="email" type="email" autoComplete="email" required/></label>{mode!=="forgot"&&<label>Парола<input name="password" type="password" autoComplete={mode==="login"?"current-password":"new-password"} minLength={8} required/></label>}<button className="button dark auth-submit" disabled={busy}>{busy?"Моля, изчакай…":mode==="login"?"Вход":mode==="register"?"Регистрация":"Изпрати инструкции"}</button></form>{error&&<p className="auth-error" role="alert">{error}</p>}{success&&<p className="auth-success" role="status">{success}</p>}<div className="auth-switch">{mode==="login"&&<><button onClick={()=>setMode("forgot")}>Забравена парола</button><button onClick={()=>setMode("register")}>Нямаш профил? Регистрация</button></>}{mode!=="login"&&<button onClick={()=>setMode("login")}>Обратно към вход</button>}</div></section></main>
}
