"use client"
import{useState,type ReactNode}from"react"
import{useCommerce}from"./CommerceProvider"
const tickerItems=["Безплатна доставка над €250","30 дни за връщане","Над 20 години опит","Над 20 000 доволни клиенти","Естествена кожа · Малки серии"]
function TickerGroup({hidden=false}:{hidden?:boolean}){return <div className="announcement-group" aria-hidden={hidden||undefined}>{tickerItems.map(item=><span className="announcement-item" key={item}>{item}<i/></span>)}</div>}
export default function StoreShell({children}:{children:ReactNode}){
 const[menuOpen,setMenuOpen]=useState(false);const{cart,cartCount,cartBusy,cartOpen,setCartOpen,updateItem,removeItem,customer}=useCommerce()
 const close=()=>{setMenuOpen(false);setCartOpen(false)}
 return <><div className="announcement"><div className="announcement-track"><TickerGroup/><TickerGroup hidden/></div></div>
 <header className="site-header"><button className="menu-button" aria-label="Отвори менюто" onClick={()=>setMenuOpen(true)}><i/><i/></button><a className="logo" href="/"><strong>FURIA</strong> <em>LEATHER</em></a><nav aria-label="Основна навигация"><a href="/women">Жени</a><a href="/men">Мъже</a><a href="/blog">Блог</a></nav><div className="header-actions"><a className="account-link" href="/account" aria-label="Моят профил">{customer?"Профил":"Вход"}</a><button className="cart-trigger" onClick={()=>setCartOpen(true)} aria-label={`Количка с ${cartCount} продукта`}><span>Количка</span> <sup>{cartCount}</sup></button></div></header>
 {children}
 <footer><div className="footer-grid"><div><a className="logo light" href="/"><strong>FURIA</strong> <em>LEATHER</em></a><p>Кожени якета в малки серии.<br/>София, България.</p></div><div><h3>Магазин</h3><a href="/women">Жени</a><a href="/men">Мъже</a><a href="/#shop">Нови модели</a></div><div><h3>Помощ</h3><a href="/blog">Доставка и връщане</a><a href="/blog">Размери</a><a href="/blog">Грижа за кожата</a></div><div><h3>Акаунт</h3><a href="/account">Моят профил</a><a href="/account">Моите поръчки</a></div></div><div className="copyright">© 2026 Furia Leather <span>BG / EUR</span></div></footer>
 <div className={`drawer-overlay ${menuOpen||cartOpen?"open":""}`} onClick={close}/>
 <aside className={`drawer menu-drawer ${menuOpen?"open":""}`} aria-hidden={!menuOpen}><button className="drawer-close" onClick={()=>setMenuOpen(false)} aria-label="Затвори">×</button><nav><a href="/women">Жени</a><a href="/men">Мъже</a><a href="/blog">Блог</a><a href="/account">Моят профил</a></nav><p>София, България<br/>hello@furialeather.com</p></aside>
 <aside className={`drawer cart-drawer ${cartOpen?"open":""}`} aria-hidden={!cartOpen}><button className="drawer-close" onClick={()=>setCartOpen(false)} aria-label="Затвори">×</button><h2>Твоята количка <sup>{cartCount}</sup></h2>{!cart?.items?.length?<div className="empty-cart"><p>Количката ти е празна.</p><a className="button dark" href="/women">Разгледай якетата</a></div>:<div className="cart-lines">{cart.items.map(item=><article className="cart-line" key={item.id}>{item.thumbnail&&<img src={item.thumbnail} alt=""/>}<div><h3>{item.title}</h3><p>Размер: {item.variant?.title||"—"}</p><strong>€{item.unit_price}</strong><div className="quantity"><button disabled={cartBusy} onClick={()=>updateItem(item.id,item.quantity-1)}>−</button><span>{item.quantity}</span><button disabled={cartBusy} onClick={()=>updateItem(item.id,item.quantity+1)}>+</button></div><button className="remove-line" disabled={cartBusy} onClick={()=>removeItem(item.id)}>Премахни</button></div></article>)}<div className="cart-total"><span>Общо</span><strong>€{cart.total??cart.item_total}</strong></div><a className="button dark cart-checkout" href="/checkout">Към плащане</a></div>}</aside></>
}
