"use client"
import{useState,type ReactNode}from"react"
import{useCommerce}from"./CommerceProvider"
import QuickSearch from"./QuickSearch"
const tickerItems=["Безплатна доставка над €250","30 дни за връщане","Над 20 години опит","Над 20 000 доволни клиенти","Естествена кожа · Малки серии"]
function TickerGroup({hidden=false}:{hidden?:boolean}){return <div className="announcement-group" aria-hidden={hidden||undefined}>{tickerItems.map(item=><span className="announcement-item" key={item}>{item}<i/></span>)}</div>}
export default function StoreShell({children}:{children:ReactNode}){
 const[searchOpen,setSearchOpen]=useState(false);const{cart,cartCount,cartBusy,cartOpen,setCartOpen,updateItem,removeItem,customer}=useCommerce()
 const close=()=>{setSearchOpen(false);setCartOpen(false)}
 return <><div className="site-chrome"><div className="contact-strip"><div><a href="tel:+359894668387">0894 668 387</a><a href="mailto:office@furialeather.bg">office@furialeather.bg</a></div><a href="https://maps.google.com/?q=Русе,+ул.+Александровска+24" target="_blank" rel="noreferrer">Русе, ул. Александровска 24</a></div><div className="announcement"><div className="announcement-track"><TickerGroup/><TickerGroup hidden/></div></div>
 <header className="site-header"><a className="logo" href="/"><strong>FURIA</strong> <em>LEATHER</em></a><nav aria-label="Основна навигация"><a href="/women">Жени</a><a href="/men">Мъже</a><a className="outlet-link" href="/outlet">Outlet</a><a href="/blog">Блог</a></nav><div className="header-actions header-tools"><button onClick={()=>setSearchOpen(true)} aria-label="Търсене"><span className="tool-icon">⌕</span><b>Търси</b></button><a href="/favorites" aria-label="Любими"><span className="tool-icon">♡</span><b>Любими</b></a><a className="account-link" href="/account" aria-label="Моят профил"><span className="tool-icon">○</span><b>{customer?"Профил":"Вход"}</b></a><button className="cart-trigger" onClick={()=>setCartOpen(true)} aria-label={`Количка с ${cartCount} продукта`}><span className="tool-icon">▢</span><b>Кошница</b> <sup>{cartCount}</sup></button></div></header><nav className="mobile-shop-nav" aria-label="Мобилна навигация"><a href="/women">Жени</a><a href="/men">Мъже</a><a className="outlet-link" href="/outlet">Outlet</a><button onClick={()=>setSearchOpen(true)}>Търси</button></nav></div>
 {children}
 <footer><div className="footer-grid"><div><a className="logo light" href="/"><strong>FURIA</strong> <em>LEATHER</em></a><p>Кожени якета в малки серии.<br/><a href="https://maps.google.com/?q=Русе,+ул.+Александровска+24" target="_blank" rel="noreferrer">Русе, ул. Александровска 24</a><br/><a href="tel:+359894668387">0894 668 387</a><br/><a href="mailto:office@furialeather.bg">office@furialeather.bg</a></p><div className="social-links"><a href="https://www.instagram.com/furialeather/" target="_blank" rel="noreferrer" aria-label="Instagram">ig</a><a href="https://www.facebook.com/furialeather" target="_blank" rel="noreferrer" aria-label="Facebook">f</a><a href="mailto:office@furialeather.bg" aria-label="Email">@</a><a href="tel:+359894668387" aria-label="Телефон">☎</a></div></div><div><h3>Магазин</h3><a href="/women">Жени</a><a href="/men">Мъже</a><a href="/outlet">Outlet</a><a href="/#shop">Нови модели</a></div><div><h3>Информация</h3><a href="/delivery-payment">Доставка и плащане</a><a href="/returns-exchanges">Връщане и замяна</a><a href="/terms">Общи условия</a><a href="/privacy">Поверителност</a></div><div><h3>Вашият профил</h3><a href="/search">Търсене</a><a href="/favorites">Любими</a><a href="/account">Моят профил</a><a href="/account">Моите поръчки</a></div></div><div className="footer-commerce"><div><span>Доставка с</span><b className="footer-econt">ECONT</b></div><div><span>Сигурно плащане</span><div className="footer-payments"><b>VISA</b><b className="footer-mastercard"><i/><i/></b><b>Apple Pay</b><b>G Pay</b></div></div></div><div className="copyright">© 2026 Furia Leather · „Караиванов11“ ООД <span>BG / EUR</span></div></footer>
 <div className={`drawer-overlay ${searchOpen||cartOpen?"open":""}`} onClick={close}/><QuickSearch open={searchOpen} onClose={()=>setSearchOpen(false)}/>
 <aside className={`drawer cart-drawer ${cartOpen?"open":""}`} aria-hidden={!cartOpen}><button className="drawer-close" onClick={()=>setCartOpen(false)} aria-label="Затвори">×</button><h2>Твоята количка <sup>{cartCount}</sup></h2>{!cart?.items?.length?<div className="empty-cart"><p>Количката ти е празна.</p><a className="button dark" href="/women">Разгледай якетата</a></div>:<div className="cart-lines">{cart.items.map(item=><article className="cart-line" key={item.id}>{item.thumbnail&&<img src={item.thumbnail} alt=""/>}<div><h3>{item.title}</h3><p>Размер: {item.variant?.title||"—"}</p><strong>€{item.unit_price}</strong><div className="quantity"><button disabled={cartBusy} onClick={()=>updateItem(item.id,item.quantity-1)}>−</button><span>{item.quantity}</span><button disabled={cartBusy} onClick={()=>updateItem(item.id,item.quantity+1)}>+</button></div><button className="remove-line" disabled={cartBusy} onClick={()=>removeItem(item.id)}>Премахни</button></div></article>)}<div className="cart-total"><span>Общо</span><strong>€{cart.total??cart.item_total}</strong></div><a className="button dark cart-checkout" href="/checkout">Към плащане</a></div>}</aside></>
}
