import type { Product } from "../data"
export type ProductVariant={id:string;title:string;options:Array<{value:string;option?:{title?:string}}>}
export type MedusaProduct=Product&{id:string;variants:ProductVariant[];currencyCode?:string}
export type CartLine={id:string;title:string;quantity:number;unit_price:number;thumbnail?:string|null;variant?:{title?:string;product?:{handle?:string}}}
export type Cart={id:string;items:CartLine[];item_total:number;total:number;currency_code:string}
export type CompletedOrder={id:string;display_id?:number;status?:string}
export type Customer={id:string;email:string;first_name?:string|null;last_name?:string|null;phone?:string|null}
export type CustomerOrder={id:string;display_id:number;status:string;fulfillment_status?:string;payment_status?:string;total:number;currency_code:string;created_at:string}
type ApiProduct={id:string;title:string;handle:string;thumbnail?:string|null;images?:Array<{url?:string|null}>;description?:string|null;metadata?:Record<string,unknown>|null;categories?:Array<{name?:string;handle?:string}>;collection?:{title?:string;handle?:string}|null;variants?:Array<{id:string;title:string;options?:Array<{value:string;option?:{title?:string}}>;calculated_price?:{calculated_amount?:number;currency_code?:string}|null;prices?:Array<{amount:number;currency_code:string}>}>}
export const backendUrl=process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL?.replace(/\/$/,"")||""
const publishableKey=process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY||""
export const medusaConfigured=Boolean(backendUrl&&publishableKey)
const headers=(token?:string)=>({"Content-Type":"application/json","x-publishable-api-key":publishableKey,...(token?{Authorization:`Bearer ${token}`}:{})})
async function request<T>(path:string,init:RequestInit={},token?:string):Promise<T>{const response=await fetch(`${backendUrl}${path}`,{...init,headers:{...headers(token),...(init.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error((data as{message?:string}).message||"Заявката не беше успешна.");return data as T}
let regionIdPromise:Promise<string|undefined>|undefined
export function getRegionId(){if(!regionIdPromise)regionIdPromise=request<{regions?:Array<{id:string;currency_code?:string}>}>("/store/regions?limit=100").then(d=>(d.regions||[]).find(r=>r.currency_code?.toLowerCase()==="eur")?.id||d.regions?.[0]?.id).catch(()=>undefined);return regionIdPromise}
async function fetchProducts(params:Record<string,string>){const regionId=await getRegionId();const attempts=[{...params,...(regionId?{region_id:regionId}:{}),fields:"*variants.calculated_price,*variants.prices,*variants.options,*images,*options,+metadata"},{...params,...(regionId?{region_id:regionId}:{})},params];for(const query of attempts){try{return await request<{products?:ApiProduct[]}>(`/store/products?${new URLSearchParams(query)}`)}catch{}}throw new Error("Продуктите не могат да бъдат заредени.")}
function categoryOf(product:ApiProduct):"Жени"|"Мъже"{const values=[product.title,product.handle,product.metadata?.gender,product.metadata?.category,product.collection?.title,...(product.categories||[]).flatMap(c=>[c.name,c.handle])].filter(Boolean).join(" ").toLocaleLowerCase("bg");return/women|woman|жени|дам/.test(values)?"Жени":"Мъже"}
function inferredColor(product:ApiProduct){const explicit=product.metadata?.color||product.metadata?.colour;if(explicit)return String(explicit);const text=`${product.title} ${product.handle}`.toLocaleLowerCase("bg");if(/black|чер/.test(text))return"Черен";if(/cognac|коняк/.test(text))return"Коняк";if(/brown|каф|авиатор/.test(text))return"Кафяв";if(/red|червен/.test(text))return"Червен";return"Цветът от снимката"}
function meta(product:ApiProduct,key:string){const value=product.metadata?.[key];return value?String(value):undefined}
function mapProduct(product:ApiProduct):MedusaProduct{const variant=product.variants?.[0],calculated=variant?.calculated_price,fallback=variant?.prices?.[0];return{id:product.id,slug:product.handle,name:product.title,category:categoryOf(product),color:inferredColor(product),price:calculated?.calculated_amount??fallback?.amount??0,badge:meta(product,"badge"),image:product.thumbnail||product.images?.[0]?.url||"",description:product.description||"Кожено яке, създадено за дълъг живот.",material:meta(product,"material"),craftsmanship:meta(product,"craftsmanship"),lining:meta(product,"lining"),fit:meta(product,"fit"),fastening:meta(product,"fastening"),pockets:meta(product,"pockets"),origin:meta(product,"origin")||meta(product,"country_of_origin"),modelHeight:meta(product,"model_height"),modelSize:meta(product,"model_size"),variants:(product.variants||[]).map(v=>({id:v.id,title:v.title,options:v.options||[]})),currencyCode:calculated?.currency_code??fallback?.currency_code??"eur"}}
export async function getMedusaProductsPage(offset=0,limit=24){if(!medusaConfigured)return{products:[],count:0};const d=await fetchProducts({limit:String(limit),offset:String(offset)});return{products:(d.products||[]).map(mapProduct),count:(d as {count?:number}).count??(d.products||[]).length}}
export async function getMedusaProducts(){return(await getMedusaProductsPage(0,24)).products}
export async function getMedusaProduct(handle:string){if(!medusaConfigured)return null;const d=await fetchProducts({handle});return d.products?.[0]?mapProduct(d.products[0]):null}
export async function createCart(){const region_id=await getRegionId();if(!region_id)throw new Error("Липсва активен регион.");return(await request<{cart:Cart}>("/store/carts",{method:"POST",body:JSON.stringify({region_id})})).cart}
export async function ensureBulgariaCommerce(){await request("/store/ensure-bulgaria",{method:"POST",body:"{}"})}
export async function retrieveCart(id:string){return(await request<{cart:Cart}>(`/store/carts/${id}?fields=*items,*items.variant,*items.variant.product`)).cart}
export async function addCartLine(cartId:string,variantId:string){await request(`/store/carts/${cartId}/line-items`,{method:"POST",body:JSON.stringify({variant_id:variantId,quantity:1})});return retrieveCart(cartId)}
export async function completeQuickOrder(cartId:string,input:{email:string;name:string;phone:string;address:string;color:string;size:string;payment:string;notes:string;product:string}){const names=input.name.trim().split(/\s+/);const orderAddress={first_name:names[0]||input.name,last_name:names.slice(1).join(" ")||"—",phone:input.phone,address_1:input.address,city:"Русе",postal_code:"7000",country_code:"bg"};await request(`/store/carts/${cartId}`,{method:"POST",body:JSON.stringify({email:input.email,shipping_address:orderAddress,billing_address:orderAddress,metadata:{quick_order:true,quick_order_status:"Очаква потвърждение",product:input.product,color:input.color,size:input.size,payment_method:input.payment,customer_notes:input.notes}})});const shipping=await request<{shipping_options:Array<{id:string}>}>(`/store/shipping-options?cart_id=${encodeURIComponent(cartId)}`);const option=shipping.shipping_options?.[0];if(!option)throw new Error("Няма активен метод за доставка.");await request(`/store/carts/${cartId}/shipping-methods`,{method:"POST",body:JSON.stringify({option_id:option.id})});const collection=await request<{payment_collection:{id:string}}>("/store/payment-collections",{method:"POST",body:JSON.stringify({cart_id:cartId})});await request(`/store/payment-collections/${collection.payment_collection.id}/payment-sessions`,{method:"POST",body:JSON.stringify({provider_id:"pp_system_default",data:{quick_order:true,requested_method:input.payment}})});const completed=await request<{type:string;order?:CompletedOrder;error?:{message?:string}}>(`/store/carts/${cartId}/complete`,{method:"POST"});if(completed.type!=="order"||!completed.order)throw new Error(completed.error?.message||"Поръчката не може да бъде завършена.");return completed.order}
export async function updateCartLine(cartId:string,lineId:string,quantity:number){await request(`/store/carts/${cartId}/line-items/${lineId}`,{method:"POST",body:JSON.stringify({quantity})});return retrieveCart(cartId)}
export async function deleteCartLine(cartId:string,lineId:string){await request(`/store/carts/${cartId}/line-items/${lineId}`,{method:"DELETE"});return retrieveCart(cartId)}
export async function loginCustomer(email:string,password:string){return(await request<{token:string}>("/auth/customer/emailpass",{method:"POST",body:JSON.stringify({email,password})})).token}
export async function registerCustomer(input:{email:string;password:string;first_name:string;last_name:string}){const{token}=await request<{token:string}>("/auth/customer/emailpass/register",{method:"POST",body:JSON.stringify({email:input.email,password:input.password})});await request("/store/customers",{method:"POST",body:JSON.stringify({email:input.email,first_name:input.first_name,last_name:input.last_name})},token);return loginCustomer(input.email,input.password)}
export async function retrieveCustomer(token:string){return(await request<{customer:Customer}>("/store/customers/me",{},token)).customer}
export async function retrieveCustomerOrders(token:string){return(await request<{orders:CustomerOrder[]}>("/store/orders?limit=100&order=-created_at",{},token)).orders||[]}
export async function requestPasswordReset(email:string){await request("/auth/customer/emailpass/reset-password",{method:"POST",body:JSON.stringify({identifier:email})})}
export async function resetPassword(token:string,email:string,password:string){await request("/auth/customer/emailpass/update",{method:"POST",body:JSON.stringify({email,password})},token)}
export async function beginGoogleLogin(callbackUrl:string){return request<{location?:string;token?:string}>("/auth/customer/google",{method:"POST",body:JSON.stringify({callback_url:callbackUrl})})}
export async function finishGoogleLogin(query:string){return(await request<{token:string}>(`/auth/customer/google/callback?${query}`,{method:"POST"})).token}
export async function createGoogleCustomer(token:string,email:string){await request("/store/customers",{method:"POST",body:JSON.stringify({email})},token);return(await request<{token:string}>("/auth/token/refresh",{method:"POST"},token)).token}
